version: "3.8"
services:
    rabbitmq:
        image: rabbitmq:${RABBITMQ_VERSION}
        container_name: ${RABBITMQ_CONTAINER_NAME}
        restart: unless-stopped
        ports:
            - ${RABBITMQ_PORT}:5672
            - ${RABBITMQ_PORT_WEB}:15672
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
