version: "3.8"
services:
    postgresql:
        image: postgres:$POSTGRES_VERSION
        container_name: $POSTGRES_CONTAINER_NAME
        restart: always
        ports:
            - $POSTGRES_PORT:5432
        environment:
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DB=$POSTGRES_DB
        volumes:
            - ./dump:/docker-entrypoint-initdb.d/
